#!/bin/sh

updater=/Library/PreferencePanes/id-updater.prefPane/Contents/Resources/id-updater-helper
echo "Activating updater $updater"
${updater} -weekly || echo "error in command ${updater} -weekly"

version=$(defaults read $PWD/version.plist version)
echo "Setting version info for qdigidoc/qesteidutil $version"
defaults write /Library/Preferences/ee.ria.qesteidutil plugins "${version}"
defaults write /Library/Preferences/ee.ria.qdigidocclient plugins "${version}"

#/usr/bin/open 'http://appstore.com/mac/ria'
/usr/bin/open "macappstores://search.itunes.apple.com/WebObjects/MZContentLink.woa/wa/link?mt=12&path=mac%2fria"

exit 0
