#!/bin/sh

updater=/Library/PreferencePanes/id-updater.prefPane/Contents/Resources/id-updater-helper
echo "Activating updater ${updater}"
for user in $(dscl . list /Users |grep -v -e '^_.*' -e Guest -e root -e daemon -e nobody); do
    sudo -u "${user}" ${updater} -weekly || echo "error in command ${updater} -weekly"
done

version=$(defaults read $PWD/version.plist version)
echo "Setting version info for qdigidoc4 ${version}"
defaults write /Library/Preferences/ee.ria.qdigidoc4 plugins "${version}"

/usr/bin/open "macappstore://itunes.apple.com/ee/developer/ria/id556524921?mt=12"
/usr/bin/open /Applications/Utilities/TokenSigningSafariHelper.app

exit 0
