#!/bin/bash

echo 'Removing Applications'
if $(codesign -d -vv /Applications/qdigidoc4.app 2>&1 |grep --quiet "3rd Party Mac Developer Application: Riigi Infosüsteemi Amet\|Apple Mac OS Application Signing"); 
then
    echo "qdigidoc4 is appstore version";
else
    rm -rf /Applications/qdigidoc4.app;
fi

echo 'Removing IDEMIA packages'
echo y | /Library/AWP/awp_uninstall.sh
killall -9 OTCryptokiGuiSvr

echo 'Removing EstEID.tokend'
/usr/local/bin/opensc-uninstall
rm -rf /Library/Security/tokend/EstEID.tokend
rm -rf /System/Library/Security/tokend/EstEID.tokend
rm -rf /Applications/Utilities/EstEIDTokenApp.app

echo 'Clearing tokens cache'
rm -rf /var/db/TokenCache/tokens/*

echo 'Removing browser plug-ins'
rm -rf /Library/Internet\ Plug-Ins/esteidsafariplugin.webplugin \
	/Library/Internet\ Plug-Ins/esteidfirefoxplugin.* \
	/Library/Application\ Support/Mozilla/Extensions/\{ec8030f7-c20a-464f-9b0e-13a3a9e97384\}/\{aa84ce40-4253-a00a-8cd6-0800200f9a6* \
	/Library/Google/Chrome/NativeMessagingHosts/chrome-token-signing.app \
	/Library/Google/Chrome/NativeMessagingHosts/ee.ria.esteid.json \
	/Library/Application\ Support/Google/Chrome/External\ Extensions/ckjefchnfjhjfedoccjbhjpbncimppeg.json \
	/Library/Application\ Support/Mozilla/NativeMessagingHosts/ee.ria.esteid.json \
	/Library/Application\ Support/Mozilla/Extensions/\{ec8030f7-c20a-464f-9b0e-13a3a9e97384\}/\{443830f0-1fff-4f9a-aa1e-444bafbc7319\}.xpi \
	/Library/Application\ Support/Mozilla/Extensions/\{ec8030f7-c20a-464f-9b0e-13a3a9e97384\}/\{02274e0c-d135-45f0-8a9c-32b35110e10d\}.xpi \
	/Library/Application\ Support/Mozilla/PKCS11Modules/onepinopenscpkcs11.json \
	/Library/Application\ Support/Mozilla/PKCS11Modules/idemiaawppkcs11.json \
	/Applications/Utilities/TokenSigningApp.app \
	/Applications/Utilities/TokenSigningSafariHelper.app

base_ver="10.15.99"
if [ $(echo -e $base_ver"\n"$(sw_vers -productVersion) | sort -V | tail -1) == "$base_ver" ]; then 
	profiles remove --identifier ee.ria.chrome-token-signing
fi

echo 'Remove old package references'
rm -rf /var/db/receipts/ee.ria.open-eid.* \
	/var/db/receipts/ee.ria.ID-updater.* \
	/var/db/receipts/ee.ria.esteid-pkcs11* \
	/var/db/receipts/ee.ria.esteid-tokend* \
	/var/db/receipts/ee.ria.esteidfirefoxplugin.* \
	/var/db/receipts/ee.ria.esteidpkcs11loader.* \
	/var/db/receipts/ee.ria.firefox-pkcs11-loader.* \
	/var/db/receipts/ee.ria.firefox-token-signing.* \
	/var/db/receipts/ee.ria.chrome-token-signing.* \
	/var/db/receipts/ee.ria.safari-token-signing.* \
	/var/db/receipts/org.opensc-project.mac.*


if [ -e "/Library/LaunchAgents/ee.EstonianIDCard.id-updater.plist" ]; then
	echo 'Remove old updater'
	launchctl unload /Library/LaunchAgents/ee.EstonianIDCard.id-updater.plist
	rm -f /Library/LaunchAgents/ee.EstonianIDCard.id-updater.plist
fi

if [ -e "/Library/LaunchAgents/ee.ria.id-updater.plist" ]; then
	echo 'Remove old updater'
	launchctl unload /Library/LaunchAgents/ee.ria.id-updater.plist
	rm -f /Library/LaunchAgents/ee.ria.id-updater.plist
fi

exit 0
